apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: todo-app

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres.yaml
  - api.yaml
  - ingress.yaml
  - hpa.yaml

commonLabels:
  app.kubernetes.io/part-of: todo-app
